# Generated by Django 5.2.7 on 2025-11-06 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0002_commutesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commuteoption',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='commuteoption',
            name='type',
        ),
        migrations.AddField(
            model_name='commuteoption',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commuteoption',
            name='name',
            field=models.CharField(default='Legacy option', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='commuters.employee'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='commuters.commuteoption'),
        ),
    ]
