# Generated by Django 5.2.7 on 2025-11-06 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuters', '0003_alter_commuteoption_options_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('baseline_monthly_cost', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('baseline_co2_kg_per_month', models.DecimalField(decimal_places=1, default=220, max_digits=8)),
                ('payroll_tax_rate', models.DecimalField(decimal_places=2, default=7.65, max_digits=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='commuteoption',
            name='co2_kg_per_month',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='commuteoption',
            name='monthly_cost_after_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='commuteoption',
            name='monthly_cost_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='commuteoption',
            name='points_per_session',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='commuters.commuteoption'),
        ),
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profiles', to='commuters.office')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='commuters.office'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('target_points', models.IntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='commuters.office')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
