# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api:
    name: API (Django)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # If you haven't created requirements yet, this won't fail the job.
          # Remove "|| true" once requirements.txt exists.

      - name: Run tests
        run: |
          pytest -q || echo "No tests yet"

  web:
    name: Web (Next.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Typecheck & build
        run: |
          npm run typecheck || echo "no typecheck script yet"
          npm run build || echo "no build yet"
